# Generated by Django 4.0.4 on 2022-06-22 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_remove_personas_fecha_nacimiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
