# Generated by Django 4.0.4 on 2022-07-01 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_delete_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textos',
            name='nombre',
        ),
    ]
