# Generated by Django 4.0.4 on 2022-07-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_remove_textos_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='textos',
            name='autor',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='textos',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='textos',
            name='subtitulo',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='textos',
            name='titulo',
            field=models.CharField(default='', max_length=20),
        ),
    ]
