# Generated by Django 4.0.4 on 2022-07-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0005_textos_autor_textos_fecha_textos_subtitulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textos',
            name='subtitulo',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='textos',
            name='titulo',
            field=models.CharField(default='', max_length=40),
        ),
    ]
