# Generated by Django 4.0.4 on 2022-07-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0006_alter_textos_subtitulo_alter_textos_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textos',
            name='subtitulo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='textos',
            name='titulo',
            field=models.CharField(default='', max_length=80),
        ),
    ]
