# Generated by Django 4.0.4 on 2022-07-02 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0008_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
