# Generated by Django 4.0.4 on 2022-07-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0009_delete_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='texto',
            field=models.CharField(default='', max_length=200),
        ),
    ]
